export const links = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-Printed-Tshirt--1--1675842429.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-D-240x350-ovrszd-1676537032.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Sweatshirt---Hoodies-1672915219.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-joggers-1668772677.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/vests-category-icon-1675844905.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Full-Sleeve-Tshirt-1673010261-1676129954.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-printed-tshirts-1668773246.jpg",
  },
  {
    image:
      " https://images.bewakoof.com/uploads/grid/app/category-box-new-ovrszd-w-1676463439.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Sweatshirt---Hoodies-women-1673010262.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-joggers-1668773245.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-w-dresses-1675144062.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-boyfriend-tees-1675319582.jpg",
  },
];

export const collections = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/new-mid-banner-b3at999-1676885542.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/new-mid-banner-2023-BTS-01-1677128271.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/new-mid-banner-2023-MEN-VEST-02-1676611750.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/1x1-The-Ultimate-Joggers-common--1--1676898158.gif",
  },
];

export const catToBag = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Jeans-men-1672915059.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Jackets-1672915210.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-pyjamas-1668772679.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-2-1669360792.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-w-pyjamas-2-1675144063.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Jackets-women-1673010261.png",
  },
];

export const slider1 = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/1x1-jumbo-prints-common-02-1677000028.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/static-1x1-Polo-01-1677000030.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/1x1-tshirt-dresses-1677000030.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/joggers--1--1676971650.jpg",
  },
];

export const slider2 = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/oversized-tee-new--1--1676901314.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/static-1x1-LimitedOffer-04-1676028999.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/full-sleeve-banner-2-1676443809.jpg",
  },

  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/1x1Banner-GraphicBags-01-1676555256.jpg",
  },
];

export const accessories = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-Mobile-covers-1672907490.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-new-mugs-1673005212.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-backpacks-1672907481.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-notebooks-1672896372.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-sliders-men-1672907494.png",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/category-box-caps-1672907483.png",
  },
];
export const collections2 = [
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/new-mid-banner-boyfriendtees-1674483112.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/MIdSizeBanner-TrendyToppers-1676223605.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/plus-size-mid-banner-1671788992.jpg",
  },
  {
    image:
      "https://images.bewakoof.com/uploads/grid/app/midsizebanner-common-jeans-1675666577.jpg",
  },
];
